# ===================== Mandatory Values =======================
# This is required, a user can pre-allocate a floating IP and set it here
# to be used by the cluster. If this is not set, a new floating IP will be
# allocated for the cluster each time it is created and clusters cannot .
apiServer:
  floatingIP: "130.246.80.99"

# --------------------------- Optional Values -------------------------
# List of comma separated additional packages to install on cluster nodes
additionalPackages: []

controlPlane:
  # The number of control plane machines to deploy
  # For high-availability, this should be greater than 1
  # For etcd quorum, it should be odd - usually 3, or 5 for very large clusters
  machineCount: 3
  # The flavor to use for control plane machines
  machineFlavor: l3.nano

  # defaults cause OutofSync issues in argocd
  remediationStrategy:
    retryPeriod: 20m0s
    minHealthyPeriod: 1h0m0s

# The Kubernetes version of the cluster
# This should match the version of kubelet and kubeadm in the image
# and will be automatically updated by us
kubernetesVersion: "1.31.8"
# The name of the image to use for cluster machines
machineImage: "capi-ubuntu-2204-kube-v1.31.8-2025-05-02"

addons:
  # Monitoring sets up kube-prometheus-stack and loki-stack.
  # Monitoring is disabled by default because of cinder issues
  monitoring:
    enabled: false

  # Ingress is preferred, as it allows you to use DNS to locate multiple
  # services behind a single FIP, and makes TLS trivial
  # see https://stfc.atlassian.net/wiki/spaces/CLOUDKB/pages/309854262/CAPI+Ingress
  ingress:
    enabled: false
    nginx:
      release:
        values:
          controller:
            service:
              loadBalancerIP: # "130.x.y.z"

# Settings for node-level registry auth if using a private registry
registryAuth:
  {}
  # registry-1.docker.io:
  #   username: "<username>"
  #   password: "<password>"

# The name of the SSH key to inject into cluster machines, this can be
# left blank if a user does not require SSH access to the machines
machineSSHKeyName:
