# The PEM-encoded CA certificate for openstack.stfc.ac.uk
# this expires 2023-12-05T23:59:59Z (UTC)
# This allows a user to skip adding verify: false
# by pre-bundling the image for everyone
cloudCACert: |
  -----BEGIN CERTIFICATE-----
  MIIIBTCCBe2gAwIBAgIRAPCLUpU+riVHiL9LCuU6g5wwDQYJKoZIhvcNAQEMBQAw
  RDELMAkGA1UEBhMCTkwxGTAXBgNVBAoTEEdFQU5UIFZlcmVuaWdpbmcxGjAYBgNV
  BAMTEUdFQU5UIE9WIFJTQSBDQSA0MB4XDTI0MTEwNTAwMDAwMFoXDTI1MTEwNTIz
  NTk1OVowaDELMAkGA1UEBhMCR0IxEjAQBgNVBAgTCVdpbHRzaGlyZTEjMCEGA1UE
  ChMaVUsgUmVzZWFyY2ggYW5kIElubm92YXRpb24xIDAeBgNVBAMTF3NlcnZpY2Ux
  Lm51YmVzLnJsLmFjLnVrMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
  1zcjKfyWC38pvZlMZpGh1bIb9+qKlJOBnHeK1jY4tCgQ0STfZUAiPOy0BuW530ze
  k7969MwuYO7d7gvXXwo9l4ArWGQsUBF4O6q4a1PTkKDyih9aXMi1E5TuVVKhGcsG
  NU2zi6w1EekUiAMMMLylFaUW6dyfMqTiWH05/I/uq6ZceiOKCcIlSI8F5OaMyMDF
  uQftS9c96znPqXhze6aQHU+fVdY9cbXrDWxiVHOF0El/4UMnFShawqK1CJ+2jasd
  yvXUvCQGrxXfdSr+oiwpk1it+mowVNA35wirYoDfajBaDlq6RxKv5j66LQEs3W6O
  qj4xX0eNpE4ITy+IOSwppQIDAQABo4IDzDCCA8gwHwYDVR0jBBgwFoAUbx01SRBs
  MvpZoJ68iugflb5xegwwHQYDVR0OBBYEFJsLIgHAdmpHXwzZrtIW0BJLk2O1MA4G
  A1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMB
  BggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysGAQQBsjEBAgJPMCUwIwYIKwYBBQUH
  AgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BTMAgGBmeBDAECAjA/BgNVHR8EODA2
  MDSgMqAwhi5odHRwOi8vR0VBTlQuY3JsLnNlY3RpZ28uY29tL0dFQU5UT1ZSU0FD
  QTQuY3JsMHUGCCsGAQUFBwEBBGkwZzA6BggrBgEFBQcwAoYuaHR0cDovL0dFQU5U
  LmNydC5zZWN0aWdvLmNvbS9HRUFOVE9WUlNBQ0E0LmNydDApBggrBgEFBQcwAYYd
  aHR0cDovL0dFQU5ULm9jc3Auc2VjdGlnby5jb20wggF8BgorBgEEAdZ5AgQCBIIB
  bASCAWgBZgB1AN3cyjSV1+EWBeeVMvrHn/g9HFDf2wA6FBJ2Ciysu8gqAAABkvuJ
  pHkAAAQDAEYwRAIgc+o49V0kR2g2QnEJuuHLPIakDdoAp+ZKIZNK9QUdv/YCIBY5
  Hf6CZcF8y6E0J4RRzfaXw9iNlL1szaWPBHQVr7wmAHUAzPsPaoVxCWX+lZtTzumy
  fCLphVwNl422qX5UwP5MDbAAAAGS+4mkKgAABAMARjBEAiBoleYmz9BGomQEhWOS
  ihjR2mUjh4kVKBHDW8ivkMqBVAIgLHlmJ2uEGyvC4qmbSnxv+PlMCSrHK/8wDhhz
  RF/8saAAdgAS8U40vVNyTIQGGcOPP3oT+Oe1YoeInG0wBYTr5YYmOgAAAZL7iaQH
  AAAEAwBHMEUCIAtQ1Weja9l+jESf3syHq9Nc0gRXUEXAxBO3qKqyNG1rAiEAspRr
  8b+3ygmVm9TsGHfiEaHBBMTtnZxpOI+XVoP/tHAwgcUGA1UdEQSBvTCBuoIXc2Vy
  dmljZTEubnViZXMucmwuYWMudWuCFGNsb3VkLm51YmVzLnJsLmFjLnVrghZjbG91
  ZC5udWJlcy5zdGZjLmFjLnVrghBjbG91ZC5zdGZjLmFjLnVrghNuZXdjbG91ZC5z
  dGZjLmFjLnVrghhvcGVuc3RhY2subnViZXMucmwuYWMudWuCGm9wZW5zdGFjay5u
  dWJlcy5zdGZjLmFjLnVrghRvcGVuc3RhY2suc3RmYy5hYy51azANBgkqhkiG9w0B
  AQwFAAOCAgEAHWDDspdJ4A6sNHqael+dD8j5acMr4qu1CX6qlN6s+a3CoMDWDWn3
  kB6klpV4cNs0zph77nTc+rq97uX0TtKLtw0d7va1EBMdBgHCKEfEq6uhO6S9DrE5
  /85XORmVjhGPcnPh3x9WzYH3gGrqZsFY8XQ1pllwwDSCUngwEp3BkxZclXwA31fd
  nwuNjjD0ZsGQVnz7OS258s+3S7E9dDgvFdUh/als0z80GsZuHxNUBhdv0otTxjqd
  lS+Fbd7D0DAQi0Zek2jfQDi3LoZopYdXDjmOqlzots8Fnp9QyRoLuOXzJCK6GD4R
  oU87Nn7tQ3bc0L68xk7+tEaRhG7vAlPzhPgaDYf2uRMk/tlf2UHKKigyW1tOjmPj
  7XU14FQrDmlPtJi7aoTgXaia9VIn5/noXydPYG92fIoqDaEN1/lYdc9wSMmSzSUn
  QYbAX8CYBiAxf7msHvWJ0tBxKGETkB1hM1rF4mr+SXQc+KCE9lJY0WfqSvfrTQfe
  gQK6M8YWyJueb75rk/aIhEud1svNm0fYOhI76vsVp1oHO7FDhBWYexn0ytJoIlje
  BtqFE7/dp3hZRd+AfFCyaz9n7Y3qkcfndYELIVZch0IapcBJzqGbrgc2z6ND6Dmo
  otryEeoZYD/PlTY0cv32scHRML6/9EaJTsywqeIkJqqQq5DzVOnCfus=
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIG5DCCBMygAwIBAgIQBHuLbQmxZWdCqKfBhpyfqjANBgkqhkiG9w0BAQwFADCB
  iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
  cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
  BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMjAw
  MjE4MDAwMDAwWhcNMzMwNTAxMjM1OTU5WjBEMQswCQYDVQQGEwJOTDEZMBcGA1UE
  ChMQR0VBTlQgVmVyZW5pZ2luZzEaMBgGA1UEAxMRR0VBTlQgRVYgUlNBIENBIDQw
  ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCfQj5WwXIGcoT7zvITdpnR
  8P7auxwyAmBFjTtOksiLjlXP62wum102dz70U1cvdWnrK3e32SyVHIvVVJRIeUIl
  q9cRj38gd/4t/e2etn+tpHUtL9wK5AIXs9tpIjEnw4UlcpLsVpLEiyc1Sc2XtwbC
  or7MMrOB4qVucNPF+GQHWi/Vnss5zLVzXlfuJ7A5Efx1lSeWvMkNDdHxxuv62yYs
  j+FEiY1IXjV1WyWxTlseJcazDUciw7LMK30Tp9smdONuPX6rwEVSTUiC3QzbwNaP
  4C1Um2yAEbdve4Ru/qURloHud5LkBaJTm2+MDJz+yHZf4g7lvKpbcKrf59Jg8h02
  sRipT6GA3cjpgB5RU5bnXFkn4kpT2+/P25HQFeg0lyKw8dFm864sn8a37GrWviOC
  TOCWtrrSxtvLvCy9axxgc9btrA596rMKrw2tpp42KPPRXHjaVqfLf6Wj2SCynFWx
  +insGBIikpbxxOdrt4qGEDgVdSOCN9f3b6CgyTs7PD5KlUiei05Cg7sbX/Zi9DE0
  8782f4SGsZtyn4G/rMIqxyZ8SfyQZV17c+zNkttdy93iQv+IlNJGalCM56Mmkv5n
  gRtWJXzk0stw30tVWdRSGlRVxxScfcwEF1GcfVjuyosTSnEju61Qi9N5WvhqitIX
  J/wLzkppJc77xbQX+5tinwIDAQABo4IBizCCAYcwHwYDVR0jBBgwFoAUU3m/Wqor
  Ss9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFLYgDq6jy+lVAwYTZtSsvieQVGDzMA4G
  A1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdJQQWMBQGCCsG
  AQUFBwMBBggrBgEFBQcDAjA4BgNVHSAEMTAvMC0GBFUdIAAwJTAjBggrBgEFBQcC
  ARYXaHR0cHM6Ly9zZWN0aWdvLmNvbS9DUFMwUAYDVR0fBEkwRzBFoEOgQYY/aHR0
  cDovL2NybC51c2VydHJ1c3QuY29tL1VTRVJUcnVzdFJTQUNlcnRpZmljYXRpb25B
  dXRob3JpdHkuY3JsMHYGCCsGAQUFBwEBBGowaDA/BggrBgEFBQcwAoYzaHR0cDov
  L2NydC51c2VydHJ1c3QuY29tL1VTRVJUcnVzdFJTQUFkZFRydXN0Q0EuY3J0MCUG
  CCsGAQUFBzABhhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMA0GCSqGSIb3DQEB
  DAUAA4ICAQAmUg8HhUdEzgbJQrk3G7JLuFyKJHWQ74FRHMFCorKd+h9TXoxSBOAo
  PZU5iIKv/mPXyhT+sh75NvlXr/N+d52Tx2HIY3IYWx82I0uaa0/tPKImL6ByJuqu
  mcvb2c4MqCfTGAi8kILbQt3WHK/idEiG2APMlq1YNoR3aBh7tc1rloxmQ5joEmrj
  wSoNA60AV2w9zEmi4KTYVZzsTjRgK8vh8WGQ4un3ZQhRYIVTdiI1J63kohIcpFTe
  fJyz9ip3C1Rjr5kink4bGlcxpRb1WjEs3OWhzCJSo7/ZZIIZu0pRsDKltkpNmoUQ
  5/4aIAEG9a9azLTKxTktcKOEJCOzdVIhNC/b6jrCFD7vR9v/dTI8zX9Ol1cK2nms
  k/uD5CZcvMZ6Rh/D7AS7B8dWODbN3nQPzucgdION4KHvJJe1G2SxDe+5MQO4CbwI
  WI5U+OnxKTP3vlJv2CxvP/+4Drf3hkp7YvVSZnmc9KlOeDvdC3Om9jNSw3njrEde
  foNq1eeeV89hCWKKdn05kpyitOiy7pTJJuDgVs64YGaSdQZG0E4m1bMSo13cQxYg
  J6EY3nagUJyiLzdMNuhbKlj2oXxjGLgUXYJJgSnnjqK7ldTbJDXK/qVX0gQSOr1b
  72T77sRtDcLsmkh7hYi6a+QwKARgmMLZjDirRS6ovWtH60yG2rkxBw==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIF3jCCA8agAwIBAgIQAf1tMPyjylGoG7xkDjUDLTANBgkqhkiG9w0BAQwFADCB
  iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
  cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
  BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTAw
  MjAxMDAwMDAwWhcNMzgwMTE4MjM1OTU5WjCBiDELMAkGA1UEBhMCVVMxEzARBgNV
  BAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0plcnNleSBDaXR5MR4wHAYDVQQKExVU
  aGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNVBAMTJVVTRVJUcnVzdCBSU0EgQ2Vy
  dGlmaWNhdGlvbiBBdXRob3JpdHkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
  AoICAQCAEmUXNg7D2wiz0KxXDXbtzSfTTK1Qg2HiqiBNCS1kCdzOiZ/MPans9s/B
  3PHTsdZ7NygRK0faOca8Ohm0X6a9fZ2jY0K2dvKpOyuR+OJv0OwWIJAJPuLodMkY
  tJHUYmTbf6MG8YgYapAiPLz+E/CHFHv25B+O1ORRxhFnRghRy4YUVD+8M/5+bJz/
  Fp0YvVGONaanZshyZ9shZrHUm3gDwFA66Mzw3LyeTP6vBZY1H1dat//O+T23LLb2
  VN3I5xI6Ta5MirdcmrS3ID3KfyI0rn47aGYBROcBTkZTmzNg95S+UzeQc0PzMsNT
  79uq/nROacdrjGCT3sTHDN/hMq7MkztReJVni+49Vv4M0GkPGw/zJSZrM233bkf6
  c0Plfg6lZrEpfDKEY1WJxA3Bk1QwGROs0303p+tdOmw1XNtB1xLaqUkL39iAigmT
  Yo61Zs8liM2EuLE/pDkP2QKe6xJMlXzzawWpXhaDzLhn4ugTncxbgtNMs+1b/97l
  c6wjOy0AvzVVdAlJ2ElYGn+SNuZRkg7zJn0cTRe8yexDJtC/QV9AqURE9JnnV4ee
  UB9XVKg+/XRjL7FQZQnmWEIuQxpMtPAlR1n6BB6T1CZGSlCBst6+eLf8ZxXhyVeE
  Hg9j1uliutZfVS7qXMYoCAQlObgOK6nyTJccBz8NUvXt7y+CDwIDAQABo0IwQDAd
  BgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rIDZsswDgYDVR0PAQH/BAQDAgEGMA8G
  A1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEMBQADggIBAFzUfA3P9wF9QZllDHPF
  Up/L+M+ZBn8b2kMVn54CVVeWFPFSPCeHlCjtHzoBN6J2/FNQwISbxmtOuowhT6KO
  VWKR82kV2LyI48SqC/3vqOlLVSoGIG1VeCkZ7l8wXEskEVX/JJpuXior7gtNn3/3
  ATiUFJVDBwn7YKnuHKsSjKCaXqeYalltiz8I+8jRRa8YFWSQEg9zKC7F4iRO/Fjs
  8PRF/iKz6y+O0tlFYQXBl2+odnKPi4w2r78NBc5xjeambx9spnFixdjQg3IM8WcR
  iQycE0xyNN+81XHfqnHd4blsjDwSXWXavVcStkNr/+XeTWYRUc+ZruwXtuhxkYze
  Sf7dNXGiFSeUHM9h4ya7b6NnJSFd5t0dCy5oGzuCr+yDZ4XUmFF0sbmZgIn/f3gZ
  XHlKYC6SQK5MNyosycdiyA5d9zZbyuAlJQG03RoHnHcAP9Dc1ew91Pq7P8yF1m9/
  qS3fuQL39ZeatTXaw2ewh0qpKJ4jjv9cJ2vhsE/zB+4ALtRZh8tSQZXq9EfX7mRB
  VXyNWQKV3WKdwrnuWih0hKWbt5DHDAff9Yk2dDLWKMGwsAvgnEzDHNb842m1R0aB
  L6KCq9NjRHDEjf8tM7qtj3u1cIiuPhnPQCjY/MiQu12ZIvVS5ljFH4gxQ+6IHdfG
  jjxDah2nGN59PRbxYvnKkKj9
  -----END CERTIFICATE-----

# The name of the cloud to use from the specified clouds.yaml
cloudName: openstack

# Values for the Kubernetes cluster network
kubeNetwork:
  # By default, use the private network range 10.0.0.0/12 for the cluster network
  # We split it into two equally-sized blocks for pods and services
  # This gives ~500,000 addresses in each block and distinguishes it from
  # internal net on 172.16.x.y
  pods:
    cidrBlocks:
      - 10.0.0.0/13
  services:
    cidrBlocks:
      - 10.8.0.0/13
  serviceDomain: cluster.local

clusterNetworking:
  internalNetwork: 
    nodeCidr: 192.168.128.0/17

# Settings for registry mirrors
registryMirrors:
  docker.io:
     - https://dockerhub.stfc.ac.uk
  # Upstream points these to their own mirror, null it out to prevent issues with private containers
  ghcr.io: null
  nvcr.io: null
  quay.io: null
  registry.k8s.io: null

# Settings for the Kubernetes API server
apiServer:
  # Indicates whether to deploy a load balancer for the API server
  enableLoadBalancer: true
  # Indicates whether to associate a floating IP with the API server
  associateFloatingIP: true
  # The port to use for the API server
  port: 6443

addons:
  # Enable monitoring by default, this deploys
  # https://github.com/stackhpc/capi-helm-charts/blob/main/charts/cluster-addons/README.md#monitoring-and-logging
  # and includes Loki which is required for central logging as per UKRI policy
  monitoring:
    enabled: false
  # set availabilty zone as upstream uses nova by default
  openstack:
    csiCinder:
      defaultStorageClass:
        availabilityZone: ceph
